### ISSUE TITLE
Configs

### ISSUE THREAD

**Issue by SirPlease** [LuckyServ/l4d2_luckylock_server_install_public#2]
I feel this is more of an issue you have with me rather than the project due to our differences regarding open source and private source. Regardless, the competitive rework github is meant to be a solid and public branch, it'd be much easier to work on this if you'd follow the build order and pull request configs you've added. Considering our goals align.

**Comment by LuckyServ** [comment]
I made this repository because:

- I don't want to depend on your approval for updates of my server installation process and configuration. If you want to rebase your competitive rework off of the fixes that I have applied, you're free to do so.

- I could not update my servers and have working configs with the "solid and public" branch you provided. Work had to be done to fix this so I could have updated servers. I wouldn't call your competitive rework a solid branch because of this, and I wouldn't call it public (open source) because all of the sources for the plugins you modified / created are not present.

- This repository is what I use to update / setup the servers. If people want a server configured like mine, they can just follow the installation steps from this repository. I thought I'd share the automated server setup with my fixes.  

Honestly, you need to make the sources for your plugins available if you want people to work *with* you instead of *around* you. You took the work of others, applied some modifications and only released binaries for the public to use. It directly goes against the GNU General Public License and everything it stands for.

**Comment by SirPlease** [comment]
Perhaps I worded myself poorly, I meant for its goal to be a solid and stable branch, not that jt already is.
There's currently no rush to update to this, your servers aren't broken, nor are anyone else's, my main concern was that people would start using your setup here rather than mine and would either run into issues that are related to your personal modifications or wouldn't forward actual issues to the base github. Just my initial concerns.

Either way, you've done an excellent job at setting it up for easy access and I hope you'll continue forwarding issues.

As for sources, I'm well aware of you constantly berating me for not following the license to the letter. When I first threw you the idea for this project I clearly stated all sources would be available, as they should. You declined because it'd be a waste of time, but that doesn't mean I'm not going to stick to what I said. Sources will be made available, it's just not something that happens with one commit, due to the fact I don't have easy access to all the files.

**Comment by LuckyServ** [comment]
You still haven't released the sources for the plugins you've worked on (like the sack order plugin, for instance). Actions speak louder than words.
